services:

  api:
    build: .
    ports:
      - "8080:8080"
    networks:
      - app_networks
    depends_on:
      db:
        condition: service_healthy


    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: db
      DB_DATABASE: ${MYSQL_DATABASE}
    restart: always


  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    networks:
      - app_networks
    volumes:
      - data_mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  data_mysql:

networks:
  app_networks:
    driver: bridge

