
services:

  api:
    image: martinlopez05/bazar-api:v4
    ports:
      - "8080:8080"
    networks:
      - app_networks
    depends_on:
      - db
    environment:
      DB_USERNAME: root
      DB_PASSWORD: 123456


  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: proyecto_bazar
    ports:
      - "3306:3306"
    networks:
      - app_networks
    volumes:
      - data_mysql:/var/lib/mysql


volumes:
  data_mysql:

networks:
  app_networks: